name:                rwr-toy
version:             0.1.0.0
synopsis:            Toy free monad without remorse
description:
  Example from
  http://www.haskellforall.com/2012/06/you-could-have-invented-free-monads.html
  using https://hackage.haskell.org/package/reflection-without-remorse
license:             BSD3
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - reflection-without-remorse
  - text

executables:
  rwr:
    source-dirs:      src
    main:             Main.hs
