name:                oaft
version:             0.1.0.0
synopsis:            oaft
description:         oaft
homepage:            https://github.com/genos/oaft#readme
license:             MIT
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

executables:
  oaft:
    source-dirs: src
    main: Main.hs
