[package]
name = "ra-impls"
version = "0.3.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
rand = "0.9.1"

[dev-dependencies]
pastey = "0.1.1"
proptest = "1.7.0"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
