[package]
name = "ra"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
image = "0.25.5"
peg = "0.8.4"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.5.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "none"

[profile.dev]
debug = 0
