[package]
name = "ra"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
image = "0.24.6"
peg = "0.8.1"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.2.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
