name:                edsl
version:             0.1.0.0
synopsis:            http://jtobin.ca/sharing-in-haskell-edsls
description:         Sharing in Haskell EDSL via PHOAS
homepage:            https://github.com/genos/edsl#readme
license:             MIT
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

default-extensions:
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5

ghc-options: -Wall -Werror -O2

executables:
  edsl:
    source-dirs:      src
    main:             Main.hs
