[package]
name = "bs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = {version = "0.5.1", features = ["html_reports"]}
proptest = "1.2.0"
rand = "0.8.5"
rstest = "0.18.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[[bench]]
name = "found"
harness = false

[[bench]]
name = "not_found"
harness = false
