[package]
name = "pyext-myrustlib"
version = "0.1.0"
edition = "2018"

[lib]
name = "myrustlib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]

[dependencies.rayon]
version = "1.0"
