[package]
name = "vish"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
rand = "0.9.0"
rayon = "1.10.0"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
