name:                ebmc
version:             0.1.0.0
synopsis:            Random tweet by @evilbmcats
description:         Random tweet by @evilbmcats
homepage:            https://twitter.com/@evilbmcats
license:             MIT
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - random-fu
  - scalpel
  - text

executables:
  ebmc:
    source-dirs:      src
    main:             Main.hs
