name:                du
version:             0.1.0.0
synopsis:            du in Haskell
description:         https://www.reddit.com/r/haskell/comments/cs54i/how_would_you_write_du_in_haskell/c0uvqqo
homepage:            https://github.com/genos/du#readme
license:             BSD3
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            System

dependencies:
  - base >= 4.7 && < 5
  - directory
  - unix

ghc-options: -Wall -Werror

executables:
  du:
    source-dirs:      src
    main:             Main.hs
